DROP TABLE IF EXISTS transacao CASCADE;
DROP TABLE IF EXISTS conta CASCADE;

CREATE TABLE conta (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       numero_conta VARCHAR(255),
                       titular VARCHAR(255),
                       saldo FLOAT
);

CREATE TABLE transacao (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           conta_id BIGINT NOT NULL,
                           valor FLOAT,
                           tipo VARCHAR(255),
                           data TIMESTAMP,
                           FOREIGN KEY (conta_id) REFERENCES conta(id)
);

INSERT INTO conta (numero_conta, titular, saldo) VALUES ('123456789', 'Titular 1', 1000.00);
INSERT INTO conta (numero_conta, titular, saldo) VALUES ('987654321', 'Titular 2', 500.00);
